[project]
name = "oauthmanager"
version = "0.1.12"
description = "A module for managing API authentication using 1Password and more."
readme = "README.md"
requires-python = ">=3.11.0,<4.0.0"
license = { text = "MIT" }
authors = [
  { name = "Suhail", email = "suhailece@gmail.com" },
]
dependencies = [
  "click >=8.2.1,<9.0.0",
  "cryptography >=43.0.1,<44.0.0",
  "google-api-python-client >=2.170.0,<3.0.0",
  "google-auth-httplib2 >=0.2.0,<0.3.0",
  "google-auth-oauthlib >=1.2.2,<2.0.0",
  "spotipy >=2.25.0,<3.0.0",
]
[project.scripts]
oauthmanager = "oauthmanager.cli:main"


[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
  "src/oauthmanager",
]
